[2020/05/16 11:08:23] Array: {"file":"/www/wwwroot/default/yingxiaosc/yingxiaosc/libs/log/Error.php", "line":141}
[2020/05/16 11:08:23] Array: {"errortime":"2020-05-16 11:08:23", "errornum":1, "errortype":"错误", "errormsg":"Uncaught TypeError: Argument 1 passed to Libs_Log_Error::{closure}() must be an instance of Exception, instance of ArgumentCountError given in /www/wwwroot/default/yingxiaosc/yingxiaosc/libs/log/Error.php:109\u000AStack trace:\u000A#0 [internal function]: Libs_Log_Error-\u003E{closure}(Object(ArgumentCountError))\u000A#1 {main}\u000A  thrown", "errorfile":"/www/wwwroot/default/yingxiaosc/yingxiaosc/libs/log/Error.php", "errorline":109}
